version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: csharp
    environment:
      MYSQL_ROOT_PASSWORD: helloimkwang2
      MYSQL_DATABASE: c-sharp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
